config/routes.rb
Rails.application.routes.draw do

  resources :posts

  devise_for :users

  root 'application#index'
  
  post 'comments/new(.:format)' => 'comment#create'

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :posts


end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post




end

app/models/post.rb
class Post < ActiveRecord::Base


  belongs_to :user
  has_many :categories
  has_many :comments
  scope :recent, -> {order("created_at desc").limit(3)}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  def index
    @posts = Post.recent
  end


end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

  def create
    parameters = params[:comment]
    @comment = Comment.new(parameters.permit(:content,:author))
    @comment.post = Post.find_by_id(params[:post_id])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post , notice: 'Comment was successfully created.' }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, only: [:new,:create,:edit,:update,:destroy] 


  # GET /posts
  # GET /posts.json
  def index
    
    if current_user
    
      @posts = current_user.posts
    else

      redirect_to root_path
    end
  end


  # GET /posts/1
  # GET /posts/1.json
  def show

    @comments =  @post.comments
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    
    @post = Post.new
    
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/index.html.erb
<h3>Latest posts</h3>

<% @posts.each do |post|%>

<article>

  <h2><%= link_to post.title, post_path(post) %></h2>
  <br/>
  <div>
	<%= post.content %>

  </div>
  <br/>
  <span><strong>Created by:</strong> <%=post.user.email %></span>
  <br />
  <span><strong>Published:</strong> <%=post.created_at %></span>

</article>



<% end %>

app/views/comment/:create.html.erb
<h1>Comment#:create</h1>
<p>Find me in app/views/comment/:create.html.erb</p>

app/views/comment/author:string.html.erb
<h1>Comment#author:string</h1>
<p>Find me in app/views/comment/author:string.html.erb</p>

app/views/comment/content:text.html.erb
<h1>Comment#content:text</h1>
<p>Find me in app/views/comment/content:text.html.erb</p>

app/views/comment/post_id:integer.html.erb
<h1>Comment#post_id:integer</h1>
<p>Find me in app/views/comment/post_id:integer.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogReto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<nav id="header-nav" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <ul class="nav nav-pills">
  <li class="<%= 'active' if params[:controller] == 'application' %>"><%= link_to "Blog", root_path %></li>
  </ul>
  <p class="navbar-text pull-right">
	<% if user_signed_in? %>
	Logged in as <strong><%= current_user.email %></strong>.
	<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<%= link_to "(manage posts)",posts_path %>
	<% else %>
	<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
	<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
</nav>


<div class="container">
  <div class="row">
	<div class="span12">
	  <%= yield %>
	</div>
  </div>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
	 administrator
  </h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
	  <% if user_signed_in? %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
	  <% end %>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>  
	   
	   <% if current_user.posts.count > 0%>
	   
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%=l post.created_at %></td>
		<% if user_signed_in? %>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-mini' 

		  %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
		<% else%>

		<p>This user doesn't have any posts to manage</p>

		<% end %>

		
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>
<% end %> 

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%= @post.title %></h1>
</div>

<div class="container">

  <div class="row">
	<div class="span9">
	  <%= @post.content %>
	</div>
	
	<div class="span3">
	  <dt><strong>Author:</strong></dt>
	  <dd><%= @post.user.email %></dd>
	</div>
  </div>
  <br/>
  <h3>Comments:</h3>
  <% if @comments.count > 0 %>
  <% @comments.each do |comment| %>
  <p><%= " #{comment.content} - by #{comment.author}" %></p>
  <% end %>
  <% else %>
  <span>No comments yet...</span>
  <% end%>
  
  
  <br/>
  <h4>Leave a comment: </h4>
  <%= form_for @comment, url: {controller: "comment",action: "create"}, html: {class: "nifty_form"} do |f| %>
  <br/>
  Author: <%= f.text_field :author %>
  <br/>
  Comment: <%= f.text_area :content, size: "60x12" %>
  <%= hidden_field_tag(:post_id, @post.id) %>
  <%= f.submit "Create" %>
  <% end %>


</div>